### ISSUE TITLE
No way to contact you other than this! :)

### ISSUE THREAD

**Issue by ghost** [NineWorlds/xstreamer#15]
Hi.  I think I contacted you in a different project thread.  I am working on a similar project and was wondering if you wanted to compare notes.  My version is a c++ program using the gd library to render images.  The images are then placed in your OBS scene and OBS refreshes them whenever they change.  As for a UI for it... well, I'm not that far yet!
I didn't know about the x-wing data project(s) on here so I rolled my own called libxwing.  It has a sqlite DB at its core.
I don't have my project posted anywhere yet but I intend to put it on github when it is a little further along (under a BSD-type license).

**Comment by kingargyle** [comment]
Sure always willing to collaborate.  However, I'm writing XStreamer in Java, using the Eclipse Rich Client Platform framework.  I'm running on Linux and every other program I tried that did similar Scoreboard and stream overlay functionality was locked to the Windows platform.   XStreamer will run on Windows, Mac, or Linux.

XStreamer is basically under an MIT license so people can pretty much do whatever they want with it.  One area we might be able to collaborate in the future is on a common data exchange format for some common file types.

Please keep me informed on your progress.

I also have a Facebook group that can be used to discuss the project and just the challenges that X-Wing Video Streamers run into.

https://www.facebook.com/groups/376932739310092/

**Comment by ghost** [comment]
Yes, portability is good!  Win/Mac/unix support is my goal as well.  I do my dev in a terminal with emacs, as I don’t like bloated IDE’s that get in the way.  So far, most of my dev has been done on OS X and FreeBSD, but I occasionally do builds on other systems to make sure it works.

I do like that you are using an MIT license (which is very similar to BSD).  I’m trying to avoid GPL libraries as much as possible.

**Comment by kingargyle** [comment]
Yeah.  I've been doing open source work for over 15 years, and avoid GPL and LGPL libraries like the plague.  Let me know when you get your project online and running, I'll see if I can tie some of XStreamer into it where it makes sense.

**Comment by ghost** [comment]
I just went live to do a little tweaking - https://www.twitch.tv/sirjorj

Check it out if you want/are able.

**Comment by kingargyle** [comment]
Closing.
