### ISSUE TITLE
xception in thread "main" java.lang.UnsupportedClassVersionError: us/nineworlds/xstreamer/XStreamer : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by slingpaint** [NineWorlds/xstreamer#6]
<img width="1038" alt="screen shot 2016-11-10 at 1 48 59 pm" src="https://cloud.githubusercontent.com/assets/21959796/20189752/98b2c2e8-a74c-11e6-8d3e-a7c765f9ea9d.png">

Using on mac, stats below, on version of java and mac, 
get this error in terminal when running the /xstreamer.sh 
<img width="259" alt="screen shot 2016-11-10 at 1 51 56 pm" src="https://cloud.githubusercontent.com/assets/21959796/20189845/e3dc22fa-a74c-11e6-9548-75cfa2364f24.png">

<img width="985" alt="screen shot 2016-11-10 at 1 51 32 pm" src="https://cloud.githubusercontent.com/assets/21959796/20189822/d19c81f2-a74c-11e6-873b-e02db371f0e7.png">

**Comment by kingargyle** [comment]
@slingpaint What happens at a terminal prompt if you run:

java -version

It is acting like it is finding a different version of Java.

**Comment by slingpaint** [comment]
so i updated the regular java, i found the Java JDK that i need to update, that did the trick....
