### ISSUE TITLE
Issues with XWS file

### ISSUE THREAD

**Issue by stickus** [NineWorlds/xstreamer#64]
Haven't found many XWS files that won't load, but this is one of them. No error message, just refused to load it.

`{"description":"","faction":"rebel","name":"Ray's Fair Ship","pilots":[{"name":"lowhhrick","points":29,"ship":"auzituckgunship","upgrades":{"ept":["selflessness"],"crew":["chopper"]}},{"name":"roarkgarnet","points":29,"ship":"hwk290","upgrades":{"turret":["twinlaserturret"],"crew":["niennunb"],"title":["moldycrow"]}},{"name":"biggsdarklighter","points":28,"ship":"xwing","upgrades":{"amd":["r2d6"],"ept":["swarmtactics"],"mod":["integratedastromech"]}},{"name":"captainrex","points":14,"ship":"tiefighter"}],"points":100,"vendor":{"yasb":{"builder":"(Yet Another) X-Wing Miniatures Squad Builder","builder_url":"https://geordanr.github.io/xwing/","link":"https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!251:235,-1,167:-1:-1:;46:135,32:3:-1:;4:-1,70:-1:20:U.9;224::-1:-1:&sn=Ray's%20Fair%20Ship&obs="}},"version":"0.3.0"}`

**Comment by kingargyle** [comment]
Thanks, there is a pilot that doesn't have any upgrades.  And this is causing a NullPointer Exception to be thrown.   I've got a fix for this, and will release 0.7.2 tonight with the fix.

**Comment by kingargyle** [comment]
Pushed the fix for this and will do a release tonight when I get home.

**Comment by kingargyle** [comment]
@stickus v0.7.2 is now available with the fix. https://github.com/NineWorlds/xstreamer/releases/tag/v0.7.2
