### ISSUE TITLE
XStreamer Won't Start

### ISSUE THREAD

**Issue by TiimelordHD** [NineWorlds/xstreamer#7]
[player1.txt](https://github.com/kingargyle/xstreamer/files/584330/player1.txt)
[player2.txt](https://github.com/kingargyle/xstreamer/files/584331/player2.txt)

**Comment by kingargyle** [comment]
I test both of these files out and they run as expected.

@TiimelordHD can you follow the instructions here.

http://superuser.com/a/569416

They tell how to open the command prompt from the Windows Explore and then you can run the following command from the prompt.

java -jar xstreamer-all.jar

I need the output information particularly the ugly stack trace if you get one.

**Comment by kingargyle** [comment]
@TiimelordHD also please try upgrading your java to the Java 8 JDK instead of the java runtime if you have it installed.  You can down load the JDK from here.

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by kingargyle** [comment]
I'm closing this, as @TiimelordHD said he was able to get the program working.

In addition, there is now a tutorial on how to get XStreamer running.
https://www.youtube.com/watch?v=T3vMsU59Ffg
